### ISSUE TITLE
No effect after installing/removing the Hangouts extension

### ISSUE THREAD

**Issue by Ploogle** [ejci/Chrome-Audio-EQ#23]
I had been using this extension for about a month without issue (Google Play music, HTML5 enabled in Labs) when suddenly it stopped working. The only thing I can think of that I did at the time was install and immediately uninstall the Hangouts extension. This also forced me to log into Chrome, which pulled extension/bookmark info from my other PC.

The preamp does nothing, EQ does nothing, Mono toggle does nothing. Any ideas?

**Comment by ejci** [comment]
I have no idea why it stopped working. I think somehow your HTML5 settings is not working. Can you turn off & on the HTML5 settings in google play?
Is EQ working on youtube?

**Comment by Ploogle** [comment]
It appears to be working in Youtube. I toggled HTML5 (off, save. on, save.)
in Google Play to no avail.

**Comment by ejci** [comment]
:/ Thats strange...
I will dive into it... For some reason everything is working for me :(

**Comment by DouglasBrunet** [comment]
Hey, just wanted to chime in here since I found this thread. I've been having the same problem for a while now. I did some fiddling around and found out that it was the [mini player](https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg) that was making the EQ not function. Disabling or removing the mini player app fixed it for me.

I don't think Hangouts affects it, disabling it did nothing for me. I would wager a guess that it stopped working for you because when it pulled your extensions from your other PC it probably installed the mini player too.

By the way, I noticed another problem. For some reason whenever the EQ is enabled, the particles visualizer on Google Play Music doesn't work. The album art visualizer seems unaffected. After disabling the EQ and refreshing the page, the particles visualizer works again.

Thanks for making the extension, I love using it and missed it a lot when it stopped working. Hope this helps anyone having the same issue as me.

**Comment by mason0** [comment]
Uninstalling the mini player worked for me as well, thanks @DouglasBrunet.  Weird though as I've had the mini player installed longer than this extension.

**Comment by ejci** [comment]
:/ Maybe update of mini player was conflicting with Audio EQ...
Can you pls send me link to the "mini player" so I can check the conflict and maybe fix it?

**Comment by mason0** [comment]
The mini player is enabled by the [Google Play Music](https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg?hl=en-US) extension.  To open the player itself cilck the pop-out icon in the lower right corner of the web player.  [Screenshot](http://imgur.com/ntR9RsI)

**Comment by Ploogle** [comment]
Awesome! I'll see if that works.

**Comment by Ploogle** [comment]
Disabling the Google Play extension worked! Thank you very much!

Unrelated: is there an option to donate? I'd been looking for this kind of
extension forever and would love to support this.

**Comment by ejci** [comment]
For now Im doing it for free (Im not planning to monetize it)... But if you really want to donate find a local charity and send them money.
I have a full time job and this is just something that I do for fun.

**Comment by lanceg1973** [comment]
Mini Player removal solved the no-effect EQ bug.  Works like a charm now, thanks @DouglasBrunet!
