### ISSUE TITLE
Warning: 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.

### ISSUE THREAD

**Issue by anfinil** [ejci/Chrome-Audio-EQ#24]
MacOS 10.10. Chrome Version 41.0.2272.89 (64-bit).

**Comment by skylize** [comment]
Looks like this is already fixed in master. If you want to fix your local copy from the Web Store you can make a minor change to page.js. 

Hover your mouse over "page.js" in the Console Warning to find the extension id.

In the Chrome temp folder (don't know it's location on Mac) go to 
``./User Data/Default/Extensions/{ExtensionId}/{MostRecentVersion}/page/page.js``

Somewhere around line 18 or 19, make this change:
```javascript
// look for
this.AudioContext = new webKitAudioContext()

// replace with
this.AudioContext = new AudioContext()
```
Disable, then Enable the extension to refresh.  Warning gone, everything works as expected. Likely a minor performance boost too.

**Comment by ejci** [comment]
I pushed the fix long time ago. I just need to publish new version
