### ISSUE TITLE
Chrome-Audio-EQ Disables Sound on tunein.com

### ISSUE THREAD

**Issue by nealvb** [ejci/Chrome-Audio-EQ#28]
Hi suddenly around mid April 2015 I stopped getting Audio (tunin.com) on one of my PC's via chrome
after tinkering around found it works (sound comes through) in incognito (where the plugin is diabled).

**Comment by ejci** [comment]
I will check that. Thanks for letting me know

**Comment by nealvb** [comment]
Cool
Thank you for awesome plugin

**Comment by hierovision** [comment]
I'd like to add that I also lose sound with this plugin enabled while in https://clyp.it/ and the steam web store while watching videos.

**Comment by skylize** [comment]
Line numbers below are in reference to page.js at commit f56a7ef194.

Some leads on fixing tunein.com, but haven't pinpointed it yet. It uses a stream url that looks like `http://icy1.abacast.com/kplu-jazz24mp3-32` with no trailing slash and no file extension. When the extension is running, a forward slash and semicolon are somehow getting appended to the end causing a 404, so the above url gets transformed to `http://icy1.abacast.com/kplu-jazz24mp3-32/;`  

On page load, the `audio` element has no source, so I tried conditionally adding `crossorigin` attribute (line 91)  only if it doesn't exist and commenting out the line that resets the `src` (line 96). In that case `src` is only set by the app, instead of the extension, so the first time that `if (target.src)` matches at line 93, `src` is correct without the trailing characters. However it still gets mangled before `attach()` (function lines 74-122) is called again and before the audio can start playing. Line 96 is the only time we explicitly set an element's `src` so its apparently a side effect of something else.

**Comment by skylize** [comment]
Clyp.it is another issue altogether. With the extension disabled, if I just add `crossorigin` to the `audio` element from DevTools, a clip will continue playing till if finishes, but cannot be played a second time. Additionally, if the extension is enabled, but set to disabled for that site, it still breaks playback.

**Comment by ejci** [comment]
I will release 0.3.2.1 version with fix

**Comment by skylize** [comment]
I think it's worth clarifying what was and was not fixed. The EQ still cannot actually be used on either tunein.com or on clyp.it. However fix ed49d1f makes the context menu option to "Disable for this domain" more reliable, so it's possible to use these sites without having to completely disable the extension.

**Comment by ejci** [comment]
Yes you are right. Sorry for not being clear.

**Comment by mori-honest** [comment]
this problem still not fixed?

**Comment by nealvb** [comment]
Hi just checked on tunein.com.  the following happens:

*Open Chrome (Audio EQ currently disabled)
*Go to tunein.com and stream something -- all good
*Enable Audio EQ -- all good
*Try change the EQ -- audio is not effected
*Close and reopen Chrome (Audio EQ currently enabled)
*Go to tune.com and stream something -- get error message from tunein.com "no stream available"
*Disable Audio EQ -- still same error message
*Close and reopen chrome (Audio EQ currently disabled)
*Go to tune.com and stream something -- all good

So for me no, not yet fixed.
( In fact worse than before though I'm now running via chrome signed in where as before I was not)
Pity though :( 
...as I really liked this extension.
